name: Publish NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_FILE: src/FSharp.Finance.Personal.fsproj

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      - name: Update version number
        run: |
          VERSION=${{ github.event.inputs.version }}
          echo "Updating version to $VERSION"
          sed -i "s/<Version>[0-9]\+\.[0-9]\+\.[0-9]\+<\/Version>/<Version>$VERSION<\/Version>/" ${{ env.PROJECT_FILE }}

      - name: Build
        run: dotnet build -c Release

      - name: Pack
        run: dotnet pack -c Release --no-build --output .

    #   - name: Publish NuGet package
    #     run: dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Create Git tag
        run: |
          git tag $VERSION
          git push origin $VERSION
